In [45]:
import pandas as pd
import numpy as np

In [46]:
epoch = 10
hidden_layer_size = 200
hidden_layers = 3

np.random.seed(10)

In [47]:
def import_data():
    
    train = pd.read_csv("train.csv")
    X_test = pd.read_csv("test.csv")
    
    y_train = (train["class"])
    X_train = train.drop(columns = "class")
    
    return X_train, X_test, y_train

In [48]:
X_train_, X_test_, y_train = import_data()

In [49]:
features_to_keep = ["freq", "premier_pay", "an", 
                    "depot", "marque",
                    "prix_auto", "pour_depot", "km", 
                    "sexe","ristourne", "cheque_dealer",
                    "sommes_des_couts", "terme"]
                    
X_train = X_train_[features_to_keep]
X_test = X_test_[features_to_keep]

In [50]:
dum_marque_train = (pd.get_dummies(X_train["marque"])).fillna(0)
dum_marque_test = (pd.get_dummies(X_test["marque"])).fillna(0)

In [51]:
X_train = (pd.concat([X_train.drop(columns = ["marque"]), dum_marque_train], axis = 1))
X_test = (pd.concat([X_test.drop(columns = ["marque"]), dum_marque_test], axis = 1))

In [52]:
good_col = []
for col in X_train.columns.values:
    if col in X_test.columns.values:
        good_col.append(col)

X_train = X_train[good_col]

In [53]:
new_freq_train = X_train["freq"].replace(['Par jour(s)', 'Mensuelle'], [0,1])
new_freq_test = X_test["freq"].replace(['Par jour(s)', 'Mensuelle'], [0,1])

X_train = (pd.concat([X_train.drop(columns = ["freq"]), new_freq_train], axis = 1))
X_test = (pd.concat([X_test.drop(columns = ["freq"]), new_freq_test], axis = 1))

In [54]:
print("X_train", (X_train.shape))
print("X_test", (X_test.shape))

X_train (1098, 37)
X_test (175, 37)

In [72]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [83]:
synA = 2*np.random.random((37,hidden_layer_size)) - 1
synB = 2*np.random.random((hidden_layer_size,1)) - 1

def train_model():
    global synA
    global synB
    
    a = X_train
    b = y_train

    list_of_error_l1=[]
    list_of_error_l2=[]

    for j in range(600):

        l0 = a
        l1 = nonlin(np.dot(l0, synA))
        l2 = nonlin(np.dot(l1, synB))

        l2_error = b - l2
        if (j % 10 == 0):
            print ("Error: " + str(np.mean(np.abs(l2_error))))

        l2_delta = l2_error*nonlin(l2, deriv=True)
        l1_error = l2_delta.dot(synB.T)
        l1_delta = l1_error * nonlin(l1,deriv=True)

        #update weights
        synB += l1.T.dot(l2_delta)
        synA += l0.T.dot(l1_delta)

        list_of_error_l1.append(str(np.mean(np.abs(l1_error))))
        list_of_error_l2.append(str(np.mean(np.abs(l2_error))))

In [84]:
train_model()

UnboundLocalError: local variable 'synA' referenced before assignment

In [80]:
y_test = []
threshold = 0.5
for test_id in range(len(X_test)):
    l0 = X_test.iloc[test_id].values
    l1 = nonlin(np.dot(l0, synA))

    l2 = nonlin(np.dot(l1, synB))
    if l2[0] > 0.4:
        l2[0] = 1
    else :
        l2[0] = 0

    y_test.append(int(l2[0]))
y_test = np.nan_to_num(y_test)
print(len(y_test))
print(len(X_test_["id"]))

175
175

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """

In [81]:
final_result_01 = pd.concat([pd.DataFrame(y_test), X_test_["id"]], axis = 1)
final_result_01 = final_result_01.rename(columns = {0: "class"})

In [76]:
type(final_result_01)

pandas.core.frame.DataFrame

In [77]:
final_result_01.to_csv("final_result_02.csv",index = False, sep = ',')

In [78]:
len(final_result_01[final_result_01["class"] == 1.0]) / len(final_result_01["class"])

0.7714285714285715

In [131]:
final_result_01

     class    id
0        1   271
1        0   139
2        1   993
3        0   613
4        0     7
5        1    52
6        1  1054
7        0   575
8        1   326
9        1   179
10       1   242
11       1  1168
12       1   869
13       0    67
14       1  1204
15       0   394
16       1   827
17       1   229
18       1   168
19       1     5
20       0    76
21       0   445
22       0  1721
23       1   263
24       0   448
25       1  1320
26       0    96
27       0  1752
28       1   290
29       1   262
..     ...   ...
145      0   195
146      1   232
147      0  1772
148      0   598
149      0   421
150      0    58
151      1  1126
152      0    24
153      1   728
154      0   500
155      1   408
156      0   699
157      0   212
158      0    17
159      0   150
160      1    21
161      0   583
162      0   381
163      0    35
164      0   585
165      0    77
166      0   312
167      0   572
168      0   133
169      0  1646
170      0   158
171      1   110
172      0    89
173      0   172
174      1   386

[175 rows x 2 columns]